added funny -er feature back, 1 in 1000 change of going off
CVScholtisek/baidbotDiscord pull request #1
Opened 2023-11-27 04:56 UTC by TheVanko

no idea if it actually works :3

2023-11-27 04:57 UTC, Git-baid commented
ok

2023-11-28 02:02 UTC, Git-baid requested changes
probably should change the variable from 'word' to something else since word is already defined

2023-11-28 02:18 UTC, TheVanko commented
changed it

2023-11-28 02:19 UTC, Git-baid approved these changes

2023-11-28 02:19 UTC, merged